### ISSUE TITLE
wasm-bindgen support

### ISSUE THREAD

**Issue by seunlanlege** [niklasad1/reconnecting-jsonrpsee-ws-client#22]
After briefly browsing through the code, doesn't seem there are any critical code paths that don't have a wasm friendly alternative. This would allow us use subxt in the browser.

**Comment by niklasad1** [comment]
Yepp, you are correct but sure it shouldn't be hard to add support WASM.

The end goal is still to have a better variant of this crate integrated directly in subxt.

**Comment by seunlanlege** [comment]
> Yepp, you are correct but sure it shouldn't be hard to add support WASM (std), lemme fix that.
> 
> The end goal is still to have a better variant of this crate integrated directly in subxt.

Yeah i also went ahead and started working on it. I have a fork of `rust-tokio-retry` (which imo should just be called `futures-retry`) that supports wasm. Lemme know how you wanna coordinate, we could also chat on element
