### ISSUE TITLE
Publish crate

### ISSUE THREAD

**Issue by ara-selini** [niklasad1/reconnecting-jsonrpsee-ws-client#6]
Hello, any chance you could please publish the current version of the code? I feel it's at a pretty usable state already.

**Comment by niklasad1** [comment]
Sure, I was waiting for subxt to upgrade jsonrpsee to v0.21 because the websocket ping/pongs are improved.

**Comment by niklasad1** [comment]
Published

**Comment by ara-selini** [comment]
Thank you!
